// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkTeamMembership = `-- name: CheckTeamMembership :one
SELECT EXISTS (
  SELECT 1
  FROM team_membership
  WHERE team_id = $1
    AND user_id = $2
)
`

type CheckTeamMembershipParams struct {
	TeamID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) CheckTeamMembership(ctx context.Context, arg CheckTeamMembershipParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkTeamMembership, arg.TeamID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getTeamMembershipRole = `-- name: GetTeamMembershipRole :one
SELECT role
FROM team_membership
WHERE team_id = $1
  AND user_id = $2
`

type GetTeamMembershipRoleParams struct {
	TeamID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetTeamMembershipRole(ctx context.Context, arg GetTeamMembershipRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getTeamMembershipRole, arg.TeamID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listAppsByTeam = `-- name: ListAppsByTeam :many
SELECT
  id,
  team_id,
  slug,
  name,
  repo_url,
  repo_default_branch,
  image_ref,
  builder,
  status,
  created_at,
  updated_at
FROM app
WHERE team_id = $1
  AND slug > $2
ORDER BY slug
LIMIT $3
`

type ListAppsByTeamParams struct {
	TeamID  pgtype.UUID
	Column2 string
	Limit   int32
}

type ListAppsByTeamRow struct {
	ID                pgtype.UUID
	TeamID            pgtype.UUID
	Slug              string
	Name              pgtype.Text
	RepoURL           pgtype.Text
	RepoDefaultBranch pgtype.Text
	ImageRef          pgtype.Text
	Builder           pgtype.Text
	Status            pgtype.Text
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) ListAppsByTeam(ctx context.Context, arg ListAppsByTeamParams) ([]ListAppsByTeamRow, error) {
	rows, err := q.db.Query(ctx, listAppsByTeam, arg.TeamID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAppsByTeamRow
	for rows.Next() {
		var i ListAppsByTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Slug,
			&i.Name,
			&i.RepoURL,
			&i.RepoDefaultBranch,
			&i.ImageRef,
			&i.Builder,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findCliTokenByID = `-- name: FindCliTokenByID :one
SELECT
  id,
  owner_user_id,
  team_id,
  kind,
  name,
  token_hash,
  scopes,
  created_at,
  last_used_at,
  expires_at,
  revoked_at
FROM cli_token
WHERE id = $1
`

type FindCliTokenByIDRow struct {
	ID          pgtype.UUID
	OwnerUserID pgtype.UUID
	TeamID      pgtype.UUID
	Kind        string
	Name        string
	TokenHash   string
	Scopes      []string
	CreatedAt   pgtype.Timestamptz
	LastUsedAt  pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
}

func (q *Queries) FindCliTokenByID(ctx context.Context, tokenID string) (FindCliTokenByIDRow, error) {
	row := q.db.QueryRow(ctx, findCliTokenByID, tokenID)
	var i FindCliTokenByIDRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.TeamID,
		&i.Kind,
		&i.Name,
		&i.TokenHash,
		&i.Scopes,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const listUserTeams = `-- name: ListUserTeams :many
SELECT
  t.id,
  t.slug,
  t.name,
  t.plan,
  t.archived_at,
  tm.user_id,
  tm.role,
  tm.joined_at,
  tm.invited_at
FROM team_membership tm
JOIN team t ON t.id = tm.team_id
WHERE tm.user_id = $1
  AND ($2::citext IS NULL OR t.slug > $2)
ORDER BY t.slug
LIMIT $3
`

type ListUserTeamsParams struct {
	UserID  pgtype.UUID
	Column2 string
	Limit   int32
}

type ListUserTeamsRow struct {
	ID         pgtype.UUID
	Slug       string
	Name       string
	Plan       string
	ArchivedAt pgtype.Timestamptz
	UserID     pgtype.UUID
	Role       string
	JoinedAt   pgtype.Timestamptz
	InvitedAt  pgtype.Timestamptz
}

func (q *Queries) ListUserTeams(ctx context.Context, arg ListUserTeamsParams) ([]ListUserTeamsRow, error) {
	rows, err := q.db.Query(ctx, listUserTeams, arg.UserID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserTeamsRow
	for rows.Next() {
		var i ListUserTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Plan,
			&i.ArchivedAt,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.InvitedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
