// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkTeamMembership = `-- name: CheckTeamMembership :one
SELECT EXISTS (
  SELECT 1
  FROM team_membership
  WHERE team_id = $1
    AND user_id = $2
)
`

type CheckTeamMembershipParams struct {
	TeamID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) CheckTeamMembership(ctx context.Context, arg CheckTeamMembershipParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkTeamMembership, arg.TeamID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listUserTeams = `-- name: ListUserTeams :many
SELECT
  t.id,
  t.slug,
  t.name,
  t.plan,
  t.archived_at,
  tm.user_id,
  tm.role,
  tm.joined_at,
  tm.invited_at
FROM team_membership tm
JOIN team t ON t.id = tm.team_id
WHERE tm.user_id = $1
  AND ($2::citext IS NULL OR t.slug > $2)
ORDER BY t.slug
LIMIT $3
`

type ListUserTeamsParams struct {
	UserID  pgtype.UUID
	Column2 string
	Limit   int32
}

type ListUserTeamsRow struct {
	ID         pgtype.UUID
	Slug       string
	Name       string
	Plan       string
	ArchivedAt pgtype.Timestamptz
	UserID     pgtype.UUID
	Role       string
	JoinedAt   pgtype.Timestamptz
	InvitedAt  pgtype.Timestamptz
}

func (q *Queries) ListUserTeams(ctx context.Context, arg ListUserTeamsParams) ([]ListUserTeamsRow, error) {
	rows, err := q.db.Query(ctx, listUserTeams, arg.UserID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserTeamsRow
	for rows.Next() {
		var i ListUserTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Plan,
			&i.ArchivedAt,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.InvitedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
