// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkTeamMembership = `-- name: CheckTeamMembership :one
SELECT EXISTS (
  SELECT 1
  FROM team_membership
  WHERE team_id = $1
    AND user_id = $2
)
`

type CheckTeamMembershipParams struct {
	TeamID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) CheckTeamMembership(ctx context.Context, arg CheckTeamMembershipParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkTeamMembership, arg.TeamID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const findCliTokenByID = `-- name: FindCliTokenByID :one
SELECT
  id,
  owner_user_id,
  team_id,
  kind,
  name,
  token_hash,
  scopes,
  created_at,
  last_used_at,
  expires_at,
  revoked_at
FROM cli_token
WHERE id = $1
`

type FindCliTokenByIDRow struct {
	ID          pgtype.UUID
	OwnerUserID pgtype.UUID
	TeamID      pgtype.UUID
	Kind        string
	Name        string
	TokenHash   string
	Scopes      []string
	CreatedAt   pgtype.Timestamptz
	LastUsedAt  pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
}

func (q *Queries) FindCliTokenByID(ctx context.Context, tokenID string) (FindCliTokenByIDRow, error) {
	row := q.db.QueryRow(ctx, findCliTokenByID, tokenID)
	var i FindCliTokenByIDRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.TeamID,
		&i.Kind,
		&i.Name,
		&i.TokenHash,
		&i.Scopes,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const findCliTokenByHash = `-- name: FindCliTokenByHash :one
SELECT
  id,
  owner_user_id,
  team_id,
  token_hash,
  scopes,
  revoked_at
FROM cli_token
WHERE token_hash = $1
`

type FindCliTokenByHashRow struct {
	ID          pgtype.UUID
	OwnerUserID pgtype.UUID
	TeamID      pgtype.UUID
	TokenHash   string
	Scopes      []string
	RevokedAt   pgtype.Timestamptz
}

func (q *Queries) FindCliTokenByHash(ctx context.Context, tokenHash string) (FindCliTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, findCliTokenByHash, tokenHash)
	var i FindCliTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.TeamID,
		&i.TokenHash,
		&i.Scopes,
		&i.RevokedAt,
	)
	return i, err
}

const getTeamMembershipRole = `-- name: GetTeamMembershipRole :one
SELECT role
FROM team_membership
WHERE team_id = $1
  AND user_id = $2
`

type GetTeamMembershipRoleParams struct {
	TeamID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetTeamMembershipRole(ctx context.Context, arg GetTeamMembershipRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getTeamMembershipRole, arg.TeamID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const isToolGranted = `-- name: IsToolGranted :one
SELECT allowed
FROM tool_grants
WHERE team_id = $1
  AND user_id = $2
  AND tool_id = $3
`

type IsToolGrantedParams struct {
	TeamID pgtype.UUID
	UserID pgtype.UUID
	ToolID string
}

func (q *Queries) IsToolGranted(ctx context.Context, arg IsToolGrantedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isToolGranted, arg.TeamID, arg.UserID, arg.ToolID)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const listAllUserGrants = `-- name: ListAllUserGrants :many
SELECT tool_id, allowed
FROM tool_grants
WHERE team_id = $1
  AND user_id = $2
ORDER BY tool_id
`

type ListAllUserGrantsParams struct {
	TeamID pgtype.UUID
	UserID pgtype.UUID
}

type ListAllUserGrantsRow struct {
	ToolID  string
	Allowed bool
}

func (q *Queries) ListAllUserGrants(ctx context.Context, arg ListAllUserGrantsParams) ([]ListAllUserGrantsRow, error) {
	rows, err := q.db.Query(ctx, listAllUserGrants, arg.TeamID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllUserGrantsRow
	for rows.Next() {
		var i ListAllUserGrantsRow
		if err := rows.Scan(&i.ToolID, &i.Allowed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppsByTeam = `-- name: ListAppsByTeam :many
SELECT
  id,
  team_id,
  slug,
  name,
  repo_url,
  repo_default_branch,
  image_ref,
  builder,
  status,
  created_at,
  updated_at
FROM app
WHERE team_id = $1
  AND slug > $2
ORDER BY slug
LIMIT $3
`

type ListAppsByTeamParams struct {
	TeamID pgtype.UUID
	Slug   string
	Limit  int32
}

type ListAppsByTeamRow struct {
	ID                pgtype.UUID
	TeamID            pgtype.UUID
	Slug              string
	Name              pgtype.Text
	RepoUrl           pgtype.Text
	RepoDefaultBranch pgtype.Text
	ImageRef          pgtype.Text
	Builder           pgtype.Text
	Status            pgtype.Text
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) ListAppsByTeam(ctx context.Context, arg ListAppsByTeamParams) ([]ListAppsByTeamRow, error) {
	rows, err := q.db.Query(ctx, listAppsByTeam, arg.TeamID, arg.Slug, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAppsByTeamRow
	for rows.Next() {
		var i ListAppsByTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Slug,
			&i.Name,
			&i.RepoUrl,
			&i.RepoDefaultBranch,
			&i.ImageRef,
			&i.Builder,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantedTools = `-- name: ListGrantedTools :many
SELECT tool_id
FROM tool_grants
WHERE team_id = $1
  AND user_id = $2
  AND allowed = true
ORDER BY tool_id
`

type ListGrantedToolsParams struct {
	TeamID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) ListGrantedTools(ctx context.Context, arg ListGrantedToolsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listGrantedTools, arg.TeamID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tool_id string
		if err := rows.Scan(&tool_id); err != nil {
			return nil, err
		}
		items = append(items, tool_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTeams = `-- name: ListUserTeams :many
SELECT
  t.id,
  t.slug,
  t.name,
  t.plan,
  t.archived_at,
  tm.user_id,
  tm.role,
  tm.joined_at,
  tm.invited_at
FROM team_membership tm
JOIN team t ON t.id = tm.team_id
WHERE tm.user_id = $1
  AND ($2::citext IS NULL OR t.slug > $2)
ORDER BY t.slug
LIMIT $3
`

type ListUserTeamsParams struct {
	UserID  pgtype.UUID
	Column2 string
	Limit   int32
}

type ListUserTeamsRow struct {
	ID         pgtype.UUID
	Slug       string
	Name       string
	Plan       string
	ArchivedAt pgtype.Timestamptz
	UserID     pgtype.UUID
	Role       string
	JoinedAt   pgtype.Timestamptz
	InvitedAt  pgtype.Timestamptz
}

func (q *Queries) ListUserTeams(ctx context.Context, arg ListUserTeamsParams) ([]ListUserTeamsRow, error) {
	rows, err := q.db.Query(ctx, listUserTeams, arg.UserID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserTeamsRow
	for rows.Next() {
		var i ListUserTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Plan,
			&i.ArchivedAt,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.InvitedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeToolGrant = `-- name: RevokeToolGrant :exec
DELETE FROM tool_grants
WHERE team_id = $1
  AND user_id = $2
  AND tool_id = $3
`

type RevokeToolGrantParams struct {
	TeamID pgtype.UUID
	UserID pgtype.UUID
	ToolID string
}

func (q *Queries) RevokeToolGrant(ctx context.Context, arg RevokeToolGrantParams) error {
	_, err := q.db.Exec(ctx, revokeToolGrant, arg.TeamID, arg.UserID, arg.ToolID)
	return err
}

const upsertToolGrant = `-- name: UpsertToolGrant :exec
INSERT INTO tool_grants (team_id, user_id, tool_id, allowed, granted_at, granted_by_actor_id)
VALUES ($1, $2, $3, $4, now(), $5)
ON CONFLICT (team_id, user_id, tool_id) DO UPDATE
SET allowed = $4, granted_at = now(), granted_by_actor_id = $5
`

type UpsertToolGrantParams struct {
	TeamID           pgtype.UUID
	UserID           pgtype.UUID
	ToolID           string
	Allowed          bool
	GrantedByActorID pgtype.UUID
}

func (q *Queries) UpsertToolGrant(ctx context.Context, arg UpsertToolGrantParams) error {
	_, err := q.db.Exec(ctx, upsertToolGrant,
		arg.TeamID,
		arg.UserID,
		arg.ToolID,
		arg.Allowed,
		arg.GrantedByActorID,
	)
	return err
}
