// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type App struct {
	ID                pgtype.UUID
	TeamID            pgtype.UUID
	Slug              string
	Name              pgtype.Text
	RepoUrl           pgtype.Text
	RepoDefaultBranch pgtype.Text
	ImageRef          pgtype.Text
	Builder           pgtype.Text
	CreatedBy         pgtype.UUID
	Status            pgtype.Text
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type AuditLog struct {
	ID          int64
	TeamID      pgtype.UUID
	ActorUserID pgtype.UUID
	SubjectType pgtype.Text
	SubjectID   pgtype.UUID
	Action      string
	Args        []byte
	Result      []byte
	PreviewID   pgtype.UUID
	TraceID     pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type CliToken struct {
	ID          pgtype.UUID
	OwnerUserID pgtype.UUID
	TeamID      pgtype.UUID
	TokenHash   string
	Name        pgtype.Text
	Scopes      []string
	LastUsedAt  pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
}

type DeployRun struct {
	ID                    pgtype.UUID
	AppID                 pgtype.UUID
	TeamID                pgtype.UUID
	CommitSha             pgtype.Text
	Ref                   pgtype.Text
	WorkflowRunID         pgtype.Int8
	Status                string
	FailureClassification pgtype.Text
	TraceID               pgtype.Text
	Events                []byte
	BuildMinutes          pgtype.Numeric
	ImageSizeBytes        pgtype.Int8
	StartedAt             pgtype.Timestamptz
	FinishedAt            pgtype.Timestamptz
	ErrorSummary          pgtype.Text
}

type DomainBinding struct {
	ID                pgtype.UUID
	AppID             pgtype.UUID
	TeamID            pgtype.UUID
	Hostname          string
	Kind              pgtype.Text
	Verified          bool
	VerificationToken pgtype.Text
	CfHostnameID      pgtype.Text
	CfDnsRecordID     pgtype.Text
	ExpiresAt         pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	VerifiedAt        pgtype.Timestamptz
}

type Preview struct {
	ID             pgtype.UUID
	TeamID         pgtype.UUID
	ActorUserID    pgtype.UUID
	Action         string
	Args           []byte
	ActionSummary  pgtype.Text
	SideEffects    []byte
	IdempotencyKey string
	LastResult     []byte
	ExpiresAt      pgtype.Timestamptz
	ConsumedAt     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

type ReconciliationJob struct {
	ID            pgtype.UUID
	TeamID        pgtype.UUID
	SubjectType   string
	SubjectID     pgtype.UUID
	Kind          string
	Attempts      int32
	NextAttemptAt pgtype.Timestamptz
	Payload       []byte
	LastError     pgtype.Text
	CreatedAt     pgtype.Timestamptz
	CompletedAt   pgtype.Timestamptz
}

type Team struct {
	ID              pgtype.UUID
	Slug            string
	Name            string
	Plan            string
	GithubInstallID pgtype.Int8
	CreatedAt       pgtype.Timestamptz
	ArchivedAt      pgtype.Timestamptz
}

type TeamMembership struct {
	TeamID    pgtype.UUID
	UserID    pgtype.UUID
	Role      string
	InvitedAt pgtype.Timestamptz
	JoinedAt  pgtype.Timestamptz
	InvitedBy pgtype.UUID
}

type ToolGrant struct {
	ID               pgtype.UUID
	TeamID           pgtype.UUID
	UserID           pgtype.UUID
	ToolID           string
	Allowed          bool
	GrantedAt        pgtype.Timestamptz
	GrantedByActorID pgtype.UUID
}

type UsageSample struct {
	ID            int64
	TeamID        pgtype.UUID
	AppID         pgtype.UUID
	SampledAt     pgtype.Timestamptz
	CpuMillicores pgtype.Int4
	MemoryBytes   pgtype.Int8
	Active        pgtype.Bool
	EgressBytes   pgtype.Int8
}

type UserAccount struct {
	ID            pgtype.UUID
	GithubLogin   pgtype.Text
	Email         pgtype.Text
	CreatedAt     pgtype.Timestamptz
	AuthStatus    pgtype.Text
	AuthScopes    []byte
	AuthExpiresAt pgtype.Timestamptz
}

type WebhookDedup struct {
	Provider   string
	DeliveryID string
	ReceivedAt pgtype.Timestamptz
}
