apiVersion: v1
kind: Service
metadata:
  name: postgres-main
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: postgres
    role: main
    app.0ops.io/managed-by: 0ops
spec:
  type: ClusterIP
  selector:
    app: postgres
    role: main
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
