apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus-recording-rules.yaml
  - prometheus-alert-rules.yaml
  - grafana-dashboards/0ops-overview.yaml
  - grafana-dashboards/0ops-deploy-pipeline.yaml
  - grafana-dashboards/0ops-product-health.yaml
  - grafana-dashboards/0ops-postgres.yaml
  - grafana-dashboards/0ops-leader-ha.yaml
  - grafana-dashboards/0ops-failure-classification.yaml

