{{- if .Values.usage.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-usage-reader" .Values.serviceAccount.name | quote }}
  labels:
    app: ops-server
    app.0ops.io/managed-by: 0ops
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name | quote }}
    namespace: {{ .Values.namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ printf "%s-usage-reader" .Values.serviceAccount.name | quote }}
{{- end }}
