apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "%s-lease" .Values.serviceAccount.name | quote }}
  namespace: {{ .Values.leaderElection.namespace | quote }}
  labels:
    app: ops-server
    app.0ops.io/managed-by: 0ops
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name | quote }}
    namespace: {{ .Values.namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ printf "%s-lease" .Values.serviceAccount.name | quote }}
