apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | quote }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: ops-server
    app.0ops.io/managed-by: 0ops
