apiVersion: v1
kind: Service
metadata:
  name: ops-server
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: ops-server
    app.0ops.io/managed-by: 0ops
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ops-server
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
