apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cloudflared-default
  namespace: {{ .Values.namespace | quote }}
spec:
  podSelector:
    matchLabels:
      app: cloudflared
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 7844
        - protocol: TCP
          port: 443
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.traefik.namespace | quote }}
      ports:
        - protocol: TCP
          port: {{ .Values.traefik.port }}
