{{- if .Values.tunnelToken }}
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-tunnel-token
  namespace: {{ .Values.namespace | quote }}
type: Opaque
stringData:
  token: {{ .Values.tunnelToken | quote }}
{{- end }}
